baseurl: "https://onspatial.github.io/geo-health-2025/"
title: "International Workshop on Geospatial Computing for Public Health@ACM SIGSPATIAL 2025"
canonifyurls: true
theme: "hugo-conference"
blackfriday:
    unsafe: true

GoogleAnalytics: ""

params:
  # Conference info
  Name: "GeoHealth@ACM SIGSPATIAL 2025"
  Description: "International Workshop on Geospatial Computing for Public Health@ACM SIGSPATIAL 2025"
  Date: "TBD"
  # Price: "Only $100" # If your event is free, just comment this line
  Venue: "Graduate by Hilton Minneapolis"
  Address: "615 Washington Ave SE"
  City:  "Minneapolis, MN"
  State: "United States"
  Images: ["/img/logo.jpg"]
  big_logo: "/images/acmsigspatial-full.png"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - intro
    - organizer    
    # - speakers
    # - schedule    
    - location
    - cfp
    - deadline
  #  - contact

  # Titles which you can translate to other languages
  Titles:
    intro: "About"
    location: "Location"
    cfp: "Call For Papers"
    organizer: "Organization Committee"
    # speakers: "Speakers"
    # schedule: "Schedule"
    deadline: "Important Dates"
    # sponsors: "Sponsors"
    # partners: "Partners"
    # contact: "Instructions for Authors"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  # CallToAction:
  #   text: "Register now"
  #   link: ""

  intro:
    text: "The 1st ACM SIGSPATIAL International Workshop on Geospatial Computing for Public Health (GeoHealth’25) focuses on all aspects of modeling, simulating, mining, and understanding the spatial processes and patterns of the spread of COVID-19 and other infectious diseases. This cross-disciplinary workshop is a forum to bring together researchers in the SIGSPATIAL community as well as researchers in epidemiology. Also, this workshop is of interest to everyone who works with infectious disease data and models (not necessarily COVID19). In addition to paper presentations, this workshop will feature invited speakers keynotes from experts across the SIGSPATIAL community and epidemiology."

  cfp:
    text: "The workshop seeks high-quality full (8-10 pages) and short (4 pages) papers that have not been published in other academic outlets and are not concurrently under peer review. Once accepted, at least one author is required to register for the workshop and the ACM SIGSPATIAL conference, as well as attend the workshop to present the accepted work which will then appear in the ACM Digital Library. As GeoHealth papers appear in the ACM SIGSPATIAL proceedings we follow the same submission process. Submission details can be found at https://sigspatial2025.sigspatial.org/camera-ready/. Following the main-conference, we also allow full papers to have a two-page appendix beyond the ten pages limit."
    keywords: ["Geospatial Analytics for Infectious Disease Surveillance",
              "Environmental Exposure Mapping (e.g., air quality, water, toxins)",
              "Modeling Health Impacts of Climate Change",
              "GIS for Health Equity and Access",
              "Spatial Decision Support Systems for Health Resource Allocation",
              "Urban Health and Built Environment Analysis",
              "Chronic Disease Mapping and Risk Factor Modeling",
              "Human Mobility and Public Health Interventions",
              "Integration of Remote Sensing and Health Data",
              "Real-time Outbreak Detection and Monitoring",
              "Geospatial Artificial Intelligence (GeoAI) in Health",
              "Privacy-aware Health Data Integration",
              "Social Determinants of Health and Spatial Inequality ",
              "Data Fusion from Wearables, EHRs, and Census Data",
              "Health Communication via Spatial Dashboards and Visualizations",
              "Spatial Epidemiology and Spatiotemporal Modeling"]

  organizer:
    general_chair: ["Joon-Seok Kim (Emory University)",
    "Taylor Anderson (George Mason University)"]
    pc_chair: ["Andreas Züfle (Emory University)",
    "Su Yeon Han (Texas State University)"]
    pc_member: [
    "Michael Desjardins (Johns Hopkins Bloomberg School of Public Health)",
    "Zipei Fan (The University of Tokyo)",
    "Song Gao (University of Wisconsin-Madison)",
    Alexander Hohl (The University of Utah)",
    "Hamdi Kavak (George Mason University)",
    "Max Lau (Emory University)",
    "Amira Roess (George Mason University)",
    "Ignacio Segovia-Dominguez	(University of Texas at Dallas)",
    "Yiqun Xie (University of Maryland)",
    "Di Yang (University of Wyoming)",
    "Jia Yu (Washington State University)"]
    webchair: ["Hossein Amiri (Emory University)"]

    
  deadline:
    submission: "August 22, 2025"
    notification: "September 26, 2025"
    camera: "October 10, 2025"
    workshopdate: "To be announced"
    submissionsite: "https://easychair.org/conferences?conf=geohealth25"
    studentgrant: "To be announced"

    
    
  #contact:
  
  speakers:
     - name: "Associate Professor Dr. Taylor Anderson, George Mason University, Department of Geography and Geoinformation Science"
       photo: "/images/keynote1.jpg"
       company: "George Mason University"
       talk: 
         title: "Modeling Spatial Heterogeneity in Health Behaviors and Disease Dynamics"
         abstrct: "Human behavior and disease outcomes are tightly coupled, making the inclusion of behavior in models of disease spread essential. Yet this remains a major challenge: limited data often force models to make simplifying assumptions about the health behaviors that drive local differences in disease trajectories. This talk focuses on methods for estimating health behaviors and disease outcomes at fine geographic scales to address this gap. Approaches for generating synthetic populations that embed behavioral and health attributes, and how these data can inform more realistic simulation modeling and small-area estimation are discussed. Together, these advances illustrate how explicitly representing spatial heterogeneity in both people and place can improve the practical utility of models for public health decision-making."
         bio: "Taylor Anderson is an Associate Professor in the Department of Geography and Geoinformation Science. She received her Ph.D. in Geography at Simon Fraser University, Canada. Her research lies at the intersection of Geographic Information Science (GISc) and urban health. Specifically, Dr. Anderson investigates the role of novel data-driven modeling and simulation approaches to better explain disease prevalence, predict future trajectories of disease, and improve public health response to diseases in both ecological and human systems. These approaches have been applied to complex problems of invasive species, infectious respiratory diseases, and non-communicable diseases."

       
  schedule:
       - title: "Opening Remarks (Session Chair: Joon-Seok)"
         time: "8:00-8:05 AM"
         file: "Frontmatter.pdf"
       - title: "Generating and Understanding Large Datasets of Social Contact Patterns from Foot-Traffic Data"
         authors: "Hossein Amiri, James Song, Li Xiong, Andreas Züfle"
         time: "8:05-8:20 AM"
         # file: "paper_1.pdf"
       - title: "Keynote"
         authors: "Associate Professor Dr. Taylor Anderson"
         bio: "Department of Geography and Geoinformation Science, George Mason University,"
         time: "8:20-9:05 AM"
       - title: "High‑Spatiotemporal‑Resolution PM2.5 Mapping in California: 6‑Hourly Estimates with 3‑km HRRR‑Smoke"
         authors: "Zhiqing Huang, Song Gao, Qunying Huang"
         time: "9:05-9:20 AM"
         # file: "paper_1.pdf"
       - title: "Equitable Access to Urgent Care: Examining Transportation Inequities and Social Vulnerabilities in Chicago through GIS"
         authors: "Emily Pokras"
         time: "9:20-9:40 AM"
         # file: "paper_1.pdf"
       - title: "Mapping HIV Vulnerability: The Role of PrEP Accessibility and Economic Inequality in Atlanta, Georgia"
         authors: "Su Yeon Han, Jeon-Young Kang, Andreas Züfle, Joon-Seok Kim"
         time: "9:40-9:55 AM"
         # file: "paper_1.pdf"
       - title: "Closing Remarks"
         time: "9:55-10:00 AM"
         
            
