baseurl: "https://onspatial.github.io/geo-health-2025/"
title: "International Workshop on Geospatial Computing for Public Health@ACM SIGSPATIAL 2025"
canonifyurls: true
theme: "hugo-conference"
blackfriday:
    unsafe: true

GoogleAnalytics: ""

params:
  # Conference info
  Name: "GeoHealth@ACM SIGSPATIAL 2025"
  Description: "International Workshop on Geospatial Computing for Public Health@ACM SIGSPATIAL 2025"
  Date: "TBD"
  # Price: "Only $100" # If your event is free, just comment this line
  Venue: "TBD"
  Address: "TBD"
  City:  "Minneapolis, MN"
  State: "United States"
  Images: ["/img/logo.jpg"]
  big_logo: "/images/acmsigspatial-full.png"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - intro
    - organizer    
    # - speakers
    # - schedule    
    - location
    - cfp
    - deadline
  #  - contact

  # Titles which you can translate to other languages
  Titles:
    intro: "About"
    location: "Location"
    cfp: "Call For Papers"
    organizer: "Organization Committee"
    # speakers: "Speakers"
    # schedule: "Schedule"
    deadline: "Important Dates"
    # sponsors: "Sponsors"
    # partners: "Partners"
    # contact: "Instructions for Authors"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  # CallToAction:
  #   text: "Register now"
  #   link: ""

  intro:
    text: "The 5th ACM SIGSPATIAL International Workshop on Spatial Computing for Epidemiology (GeoHealth’25) focuses on all aspects of modeling, simulating, mining, and understanding the spatial processes and patterns of the spread of COVID-19 and other infectious diseases. This cross-disciplinary workshop is a forum to bring together researchers in the SIGSPATIAL community as well as researchers in epidemiology. Also, this workshop is of interest to everyone who works with infectious disease data and models (not necessarily COVID19). In addition to paper presentations, this workshop will feature invited speakers keynotes from experts across the SIGSPATIAL community and epidemiology."

  cfp:
    text: "The workshop seeks high-quality full (8-10 pages) and short (4 pages) papers that have not been published in other academic outlets and are not concurrently under peer review. Once accepted, at least one author is required to register for the workshop and the ACM SIGSPATIAL conference, as well as attend the workshop to present the accepted work which will then appear in the ACM Digital Library. As GeoHealth papers appear in the ACM SIGSPATIAL proceedings we follow the same submission process. Submission details can be found at https://sigspatial2025.sigspatial.org/camera-ready/. Following the main-conference, we also allow full papers to have a two-page appendix beyond the ten pages limit."
    url: "https://onspatial.github.io/geo-health-2025/files/GeoHealth2025.pdf"
    keywords: ["Geospatial Analytics for Infectious Disease Surveillance",
              "Environmental Exposure Mapping (e.g., air quality, water, toxins)",
              "Modeling Health Impacts of Climate Change",
              "GIS for Health Equity and Access",
              "Spatial Decision Support Systems for Health Resource Allocation",
              "Urban Health and Built Environment Analysis",
              "Chronic Disease Mapping and Risk Factor Modeling",
              "Human Mobility and Public Health Interventions",
              "Integration of Remote Sensing and Health Data",
              "Real-time Outbreak Detection and Monitoring",
              "Geospatial Artificial Intelligence (GeoAI) in Health",
              "Privacy-aware Health Data Integration",
              "Social Determinants of Health and Spatial Inequality ",
              "Data Fusion from Wearables, EHRs, and Census Data",
              "Health Communication via Spatial Dashboards and Visualizations",
              "Spatial Epidemiology and Spatiotemporal Modeling"]

  organizer:
    general_chair: ["Joon-Seok Kim (Emory University)",
    "Taylor Anderson (George Mason University)"]
    pc_chair: ["Andreas Züfle (Emory University)",
    "Su Yeon Han (Texas State University)"]
    pc_member: [
    "Michael Desjardins (Johns Hopkins Bloomberg School of Public Health)",
    "Zipei Fan (The University of Tokyo)",
    "Song Gao (University of Wisconsin-Madison)",
    Alexander Hohl (The University of Utah)",
    "Hamdi Kavak (George Mason University)",
    "Max Lau (Emory University)",
    "Amira Roess (George Mason University)",
    "Ignacio Segovia-Dominguez	(University of Texas at Dallas)",
    "Yiqun Xie (University of Maryland)",
    "Di Yang (University of Wyoming)",
    "Jia Yu (Washington State University)"]
    webchair: ["Hossein Amiri (Emory University)"]

    
  deadline:
    submission: "August 9, 2025"
    notification: "September 26, 2025"
    camera: "October 10, 2025"
    workshopdate: "To be announced"
    submissionsite: "To be announced"
    studentgrant: "To be announced"

    
    
  #contact:
  
  # speakers:
  #    - name: "TBD"
  #      photo: "/images/keynote1.jpg"
  #      company: "TBD"
  #      talk: 
  #        title: "TBD"
  #   #     abstrct: ""
  #        bio: "TBD"

       
  # schedule:
  #      - title: "Opening Remarks"
  #        time: "4:00-4:10 PM"
  #        file: "Frontmatter.pdf"
  #      - title: "Keynote"
  #        authors: "TBD"
  #        bio: "Department of Epidemiology, Rollins School of Public Health, Emory University"
  #        time: "4:10-5:00 PM"
  #      - title: "TBD"
  #        authors: "TBD"
  #        time: "5:00-5:20 PM"
  #        file: "paper_1.pdf"
  #      - title: "Closing Remarks"
  #        time: "5:55-6:00 PM"
         
            
